import {dehydrate, QueryClient, useQuery} from 'react-query';
import {Box} from '@mui/material';
import type {GetServerSidePropsContext, NextPage} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import {useTranslation} from 'next-i18next';
import {serverSideTranslations} from 'next-i18next/serverSideTranslations';
import styled from 'styled-components';

import View from '@/src/components/views/home';
import {getBrands} from '@/src/services/get-brands';

const Wrap = styled.div`
  background-color: ${({theme}) => theme.palette.primary.main}; ;
`;

const Home: NextPage = () => {
  const {t} = useTranslation('common');

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <View />
    </Box>
  );
};

export default Home;

export async function getServerSideProps({req, locale}: GetServerSidePropsContext) {
  const translations = await serverSideTranslations(locale as string, ['common']);
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery('brands', getBrands);
  const dehydratedState = dehydrate(queryClient);

  return {
    props: {
      dehydratedState,
      ...translations,
    },
  };
}
